<a href="https://colab.research.google.com/github/100kuta/ArewaDS-Deep-Learning/blob/main/Copy_of_week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arewa DataScience Academy
### Deep Learning Cohort 1.0

### WEEK 1 Exercises

### Exercises:
Please, see week 1 exercises from [**Learn PyTorch for Deep Learning**: 00. Pytorch Fundamentals](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

### Additional Exercise

In [1]:
# 1. Documentation Reading

In [2]:
# 2. Create a random tensor with shape (7, 7).
import torch
Rand_Tensor = torch.rand(7,7)
Rand_Tensor

tensor([[0.4598, 0.1682, 0.2602, 0.8425, 0.2906, 0.4930, 0.5074],
        [0.4019, 0.2023, 0.7391, 0.8257, 0.4656, 0.7861, 0.8489],
        [0.6488, 0.7147, 0.9114, 0.6840, 0.7235, 0.3348, 0.9850],
        [0.2501, 0.8474, 0.1713, 0.7849, 0.8018, 0.1205, 0.3823],
        [0.6200, 0.0146, 0.2858, 0.8066, 0.5200, 0.0378, 0.8321],
        [0.9622, 0.4960, 0.9843, 0.9272, 0.6780, 0.6114, 0.0812],
        [0.0282, 0.0415, 0.0074, 0.0144, 0.6142, 0.1926, 0.1577]])

In [3]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
Tensor2 = torch.rand(1,7)
multi_tensor= torch.matmul(Rand_Tensor, Tensor2.T)
multi_tensor

tensor([[1.6276],
        [2.7310],
        [3.0839],
        [1.7608],
        [1.9115],
        [2.4311],
        [0.8251]])

In [ ]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
Rand_Tensor = torch.rand(7,7)
Tensor2 = torch.rand(1,7)
multi_tensor= torch.matmul(Rand_Tensor, Tensor2.T)
print(multi_tensor)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [4]:
''' 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
(hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.'''
print(torch.cuda.is_available())
torch.cuda.manual_seed(1234)

True


In [6]:
# 6.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
Tensor1 = torch.rand(2,3).to('cuda')
Tensor2 = torch.rand(2,3).to('cuda')
Tensor1, Tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [7]:
# 7.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
multi_tensor= torch.matmul(Tensor1, Tensor2.T)
multi_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [8]:
# 8.Find the maximum and minimum values of the output of 7.
print(multi_tensor.max())
print(multi_tensor.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


In [9]:
# 9. Find the maximum and minimum index values of the output of 7.
print(multi_tensor.argmax())
print(multi_tensor.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


In [11]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
Tensor1_10 = torch.rand(1,1,1,10)
Tensor2 = Tensor1_10.squeeze()
print(Tensor1_10, Tensor1_10.shape)
print(Tensor2, Tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
